In [1]:
import numpy as np

In [15]:
classes = range(10)

In [21]:
def _multi_argmax(arr):
    """Same as numpy.argmax but returns all occurrences of the maximum and only requires a single pass.
    From: https://stackoverflow.com/a/58652335
    """
    all_, max_ = [0], arr[0]
    for i in range(1, len(arr)):
        if arr[i] > max_:
            all_, max_ = [i], arr[i]
        elif arr[i] == max_:
            all_.append(i)
    return np.array(all_)

In [72]:
nearest_labels = np.array([5, 2, 3, 2, 4, 7, 1, 3, 3, 0, 7, 7])
nearest_scores = np.ones(nearest_labels.size)

In [135]:
# Sort the labels in ascending order (and sort distances in the same order)
sorted_labels_idx = nearest_labels.argsort()
sorted_labels, sorted_scores = nearest_labels[sorted_labels_idx], nearest_scores[sorted_labels_idx]
# Identify the indices where the sorted labels change (so we can group by labels)
change_idx = np.concatenate(([0], np.nonzero(np.diff(sorted_labels))[0] + 1))
# Calculate the total score for each label
label_scores = np.add.reduceat(sorted_scores, change_idx)
# Find the change index of the maximum score(s)
max_score_idx = change_idx[_multi_argmax(label_scores)] # self._multi_argmax
# Map the change index back to the actual label(s)
max_labels = sorted_labels[max_score_idx]
# Store class scores
scores = np.full(len(classes), -np.inf)
scores[sorted_labels[change_idx]] = label_scores
scores

array([  1.,   1.,   2.,   3.,   1.,   1., -inf,   3., -inf, -inf])

In [74]:
np.random.choice(np.argwhere(scores[0] == 1).flatten())

3

In [75]:
S = np.stack([scores] * 5)
S

array([[[0.        , 0.        , 0.        , 1.        , 0.        ,
         0.        , 0.        , 1.        , 0.        , 0.        ],
        [0.08333333, 0.08333333, 0.16666667, 0.25      , 0.08333333,
         0.08333333, 0.        , 0.25      , 0.        , 0.        ]],

       [[0.        , 0.        , 0.        , 1.        , 0.        ,
         0.        , 0.        , 1.        , 0.        , 0.        ],
        [0.08333333, 0.08333333, 0.16666667, 0.25      , 0.08333333,
         0.08333333, 0.        , 0.25      , 0.        , 0.        ]],

       [[0.        , 0.        , 0.        , 1.        , 0.        ,
         0.        , 0.        , 1.        , 0.        , 0.        ],
        [0.08333333, 0.08333333, 0.16666667, 0.25      , 0.08333333,
         0.08333333, 0.        , 0.25      , 0.        , 0.        ]],

       [[0.        , 0.        , 0.        , 1.        , 0.        ,
         0.        , 0.        , 1.        , 0.        , 0.        ],
        [0.08333333, 

In [77]:
S[:, 0, :]

array([[0., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0., 0.]])

In [96]:
S[:, 0, :] == 1

array([[False, False, False,  True, False, False, False,  True, False,
        False],
       [False, False, False,  True, False, False, False,  True, False,
        False],
       [False, False, False,  True, False, False, False,  True, False,
        False],
       [False, False, False,  True, False, False, False,  True, False,
        False],
       [False, False, False,  True, False, False, False,  True, False,
        False]])

In [98]:
X = np.array([
    [0, 1, 0, 0, 1],
    [1, 0, 0, 0, 0],
    [0, 0, 1, 1, 0],
    [1, 0, 1, 1, 0],
    [1, 1, 1, 0, 1],
    [0, 0, 0, 1, 1]
])

In [114]:
x = np.argwhere(X == 1)
x

array([[0, 1],
       [0, 4],
       [1, 0],
       [2, 2],
       [2, 3],
       [3, 0],
       [3, 2],
       [3, 3],
       [4, 0],
       [4, 1],
       [4, 2],
       [4, 4],
       [5, 3],
       [5, 4]])

In [115]:
np.split(x[:, 1], np.unique(x[:, 0], return_index=True)[1][1:])

[array([1, 4]),
 array([0]),
 array([2, 3]),
 array([0, 2, 3]),
 array([0, 1, 2, 4]),
 array([3, 4])]